
services:
  mysql:
    image: mysql:8.0.36
    container_name: mysql-dev
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    command:
      [ 'mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--lower_case_table_names=1' ]
    ports:
      - "${SQL_PORT}:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:alpine
    container_name: redis-dev
    ports:
      - "6379:6379"

  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-app-dev
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SECRET_KEY: ${SECRET_KEY}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      ACCESS_KEY: ${ACCESS_KEY}
      AWS_SECRET_KEY: ${AWS_SECRET_KEY}
      OAUTH_NAVER_CLIENT_ID: ${OAUTH_NAVER_CLIENT_ID}
      OAUTH_NAVER_CLIENT_SECRET: ${OAUTH_NAVER_CLIENT_SECRET}
    depends_on:
      - mysql
      - redis

volumes:
  mysql-data:
