services:
  redis:
    image: redis:alpine
    container_name: redis-prod
    ports:
      - "6379:6379"
    networks:
      - my-network

  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-app-prod
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:mysql://${RDS_ENDPOINT}:3306/${DB_NAME}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SECRET_KEY: ${SECRET_KEY}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      ACCESS_KEY: ${ACCESS_KEY}
      AWS_SECRET_KEY: ${AWS_SECRET_KEY}
      OAUTH_NAVER_CLIENT_ID: ${OAUTH_NAVER_CLIENT_ID}
      OAUTH_NAVER_CLIENT_SECRET: ${OAUTH_NAVER_CLIENT_SECRET}
    depends_on:
      - redis
    networks:
      - my-network

networks:
  my-network:
