services:
  mysql:
    env_file:
      - .env
    image: mysql:8.0.36
    container_name: mysql-dev
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    command:
      [ 'mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--lower_case_table_names=1' ]
    ports:
      - "${SQL_PORT}:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - my-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_PASSWORD}" ]
      timeout: 20s
      retries: 10
      interval: 10s
      start_period: 40s

  redis:
    env_file:
      - .env
    image: redis:alpine
    container_name: redis-dev
    ports:
      - "6379:6379"

  grafana:
    env_file:
      - .env
    image: grafana/grafana
    container_name: grafana-dev
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - grafana-data:/var/lib/grafana
    networks:
      - my-network

  prometheus:
    env_file:
      - .env
    image: prom/prometheus
    container_name: prometheus-dev
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./GRAFANA-PROMETHEUS-RDBMS/prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --storage.tsdb.retention.time=100d
      - --storage.tsdb.retention.size=10GB
      - --web.console.libraries=/usr/share/prometheus/console_libraries
      - --web.console.templates=/usr/share/prometheus/consoles
      - --web.enable-admin-api
    networks:
      - my-network

  query-exporter:
    env_file:
      - .env
    image: adonato/query-exporter
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    container_name: query-exporter-dev
    restart: unless-stopped
    ports:
      - "9560:9560"
    volumes:
      - ./GRAFANA-PROMETHEUS-RDBMS/query-exporter/config.yml:/etc/query-exporter/config.yml
    command:
      - --config=/etc/query-exporter/config.yml
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - my-network

volumes:
  mysql-data:
  grafana-data:
  prometheus-data:

networks:
  my-network: