apiVersion: 1

datasources:
  - name: InfluxDB-K6
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    database: k6
    user: k6
    password: k6
    isDefault: false
    jsonData:
      httpMode: GET
      keepCookies: []
    secureJsonData:
      password: k6
    version: 1
    editable: true
    uid: InfluxDB-K6
