{
 "title": "K6 Simple Dashboard",
 "tags": [
  "k6",
  "simple"
 ],
 "time": { "from": "now-10m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "총 HTTP 요청 수",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "query": "SELECT COUNT(*) FROM http_reqs" }
   ]
  },
  {
   "title": "HTTP 응답 상태",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT COUNT(*) FROM http_reqs WHERE status = '200'"
    }
   ]
  },
  {
   "title": "응답시간 통계",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "SELECT MEAN(value) FROM http_req_duration GROUP BY time(5s)"
    }
   ]
  }
 ]
}