databases:
  my-db:
    dsn: mysql://DB_USERNAME:DB_PASSWORD@mysql:3306/DB_NAME

metrics:
  user_total:
    type: gauge
    description: Total number of users

queries:
  user_count_query:
    interval: 30
    databases: [my-db]
    metrics: [user_total]
    sql: |
      SELECT COUNT(*) as user_total FROM users
